import { AdvertisementModel } from 'models/AdvertisimentModel';
import { createAsyncAction } from 'typesafe-actions';

enum ADVERTISEMENTS_ACTIONS {
  GET_USER_ADVERTISEMENTS_START = '@advertisements/GET_USER_ADVERTISEMENTS_START',
  GET_USER_ADVERTISEMENTS_SUCCESS = '@advertisements/GET_USER_ADVERTISEMENTS_SUCCESS',
  GET_USER_ADVERTISEMENTS_FAILED = '@advertisements/GET_USER_ADVERTISEMENTS_FAILED',
  POST_ADVERTISEMENT_START = '@advertisements/POST_ADVERTISEMENT_START',
  POST_ADVERTISEMENT_SUCCESS = '@advertisements/POST_ADVERTISEMENT_SUCCESS',
  POST_ADVERTISEMENT_FAILED = '@advertisements/POST_ADVERTISEMENT_FAILED',
  UPDATE_ADVERTISEMENT_START = '@advertisements/UPDATE_ADVERTISEMENT_START',
  UPDATE_ADVERTISEMENT_SUCCESS = '@advertisements/UPDATE_ADVERTISEMENT_SUCCESS',
  UPDATE_ADVERTISEMENT_FAILED = '@advertisements/UPDATE_ADVERTISEMENT_FAILED',
  DELETE_ADVERTISEMENT_START = '@advertisements/DELETE_ADVERTISEMENT_START',
  DELETE_ADVERTISEMENT_SUCCESS = '@advertisements/DELETE_ADVERTISEMENT_SUCCESS',
  DELETE_ADVERTISEMENT_FAILED = '@advertisements/DELETE_ADVERTISEMENT_FAILED',
  GET_USER_FOLLOWED_ADVERTISEMENTS_START = '@advertisements/GET_USER_FOLLOWED_ADVERTISEMENTS_START',
  GET_USER_FOLLOWED_ADVERTISEMENTS_SUCCESS = '@advertisements/GET_USER_FOLLOWED_ADVERTISEMENTS_SUCCESS',
  GET_USER_FOLLOWED_ADVERTISEMENTS_FAILED = '@advertisements/GET_USER_FOLLOWED_ADVERTISEMENTS_FAILED',
  POST_USER_FOLLOWED_ADVERTISEMENT_START = '@advertisements/POST_USER_FOLLOWED_ADVERTISEMENT_START',
  POST_USER_FOLLOWED_ADVERTISEMENT_SUCCESS = '@advertisements/POST_USER_FOLLOWED_ADVERTISEMENT_SUCCESS',
  POST_USER_FOLLOWED_ADVERTISEMENT_FAILED = '@advertisements/POST_USER_FOLLOWED_ADVERTISEMENT_FAILED',
  DELETE_USER_FOLLOWED_ADVERTISEMENT_START = '@advertisements/DELETE_USER_FOLLOWED_ADVERTISEMENT_START',
  DELETE_USER_FOLLOWED_ADVERTISEMENT_SUCCESS = '@advertisements/DELETE_USER_FOLLOWED_ADVERTISEMENT_SUCCESS',
  DELETE_USER_FOLLOWED_ADVERTISEMENT_FAILED = '@advertisements/DELETE_USER_FOLLOWED_ADVERTISEMENT_FAILED',
}

export const getUserAdvertisementsAsyncAction = createAsyncAction(
  ADVERTISEMENTS_ACTIONS.GET_USER_ADVERTISEMENTS_START,
  ADVERTISEMENTS_ACTIONS.GET_USER_ADVERTISEMENTS_SUCCESS,
  ADVERTISEMENTS_ACTIONS.GET_USER_ADVERTISEMENTS_FAILED
)<undefined, AdvertisementModel[], string>();
export const postAdvertisementAsyncAction = createAsyncAction(
  ADVERTISEMENTS_ACTIONS.POST_ADVERTISEMENT_START,
  ADVERTISEMENTS_ACTIONS.POST_ADVERTISEMENT_SUCCESS,
  ADVERTISEMENTS_ACTIONS.POST_ADVERTISEMENT_FAILED
)<undefined, AdvertisementModel, string>();
export const updateAdvertisementAsyncAction = createAsyncAction(
  ADVERTISEMENTS_ACTIONS.UPDATE_ADVERTISEMENT_START,
  ADVERTISEMENTS_ACTIONS.UPDATE_ADVERTISEMENT_SUCCESS,
  ADVERTISEMENTS_ACTIONS.UPDATE_ADVERTISEMENT_FAILED
)<undefined, AdvertisementModel, string>();
export const deleteAdvertisementAsyncAction = createAsyncAction(
  ADVERTISEMENTS_ACTIONS.DELETE_ADVERTISEMENT_START,
  ADVERTISEMENTS_ACTIONS.DELETE_ADVERTISEMENT_SUCCESS,
  ADVERTISEMENTS_ACTIONS.DELETE_ADVERTISEMENT_FAILED
)<undefined, string, string>();

export const getUserFollowedAdvertisementsAsyncAction = createAsyncAction(
  ADVERTISEMENTS_ACTIONS.GET_USER_FOLLOWED_ADVERTISEMENTS_START,
  ADVERTISEMENTS_ACTIONS.GET_USER_FOLLOWED_ADVERTISEMENTS_SUCCESS,
  ADVERTISEMENTS_ACTIONS.GET_USER_FOLLOWED_ADVERTISEMENTS_FAILED
)<undefined, AdvertisementModel[], string>();
export const postUserFollowedAdvertisementsAsyncAction = createAsyncAction(
  ADVERTISEMENTS_ACTIONS.POST_USER_FOLLOWED_ADVERTISEMENT_START,
  ADVERTISEMENTS_ACTIONS.POST_USER_FOLLOWED_ADVERTISEMENT_SUCCESS,
  ADVERTISEMENTS_ACTIONS.POST_USER_FOLLOWED_ADVERTISEMENT_FAILED
)<undefined, AdvertisementModel, string>();
export const deleteUserFollowedAdvertisementsAsyncAction = createAsyncAction(
  ADVERTISEMENTS_ACTIONS.DELETE_USER_FOLLOWED_ADVERTISEMENT_START,
  ADVERTISEMENTS_ACTIONS.DELETE_USER_FOLLOWED_ADVERTISEMENT_SUCCESS,
  ADVERTISEMENTS_ACTIONS.DELETE_USER_FOLLOWED_ADVERTISEMENT_FAILED
)<undefined, string, string>();
